.gdbinit
This commit introduces two simple features proposed in #18:
- Disabled confirmation messages (y/n)
- Automatically close GDB if the VM is closed gracefully, e.g: by receiving a SIGTERM.
=> Enhancement: GDB Confirm Off, Quit If Connection Lost

include/target/ibm/pc.h
In this commit, I have fixed the size of the kernel page pool. Before,
the I386 PC target was setting it up to 16 MB, even though only a single
page table (4 MB) was reserved for the kernel page pool at boot time.
=> [i386] Bug Fix: Bad Kernel Page Pool Size

build/makefile.or1k-pc, tools/run/run-qemu.sh
This PR introduces the environment variables necessary to build for the or1k-pc platform (#17). I also found a tiny bug in the run script that does not allows to run Qemu.
Furthermore, I've double checked the setup toolchain scripts for or1k and everything looks fine, ;-).
=> [or1k] OpenRISC Toolchain Enhancements

src/kernel/hal/arch/i386/boot.S
In this commit, I fix a bad export of symbols in the bootstrap. We were
mainly missing to export the page directory of the idle process.
=> Bug Fix: i386 Boot Symbols

include/arch/i386/mmu.h
In this commit, I fix the get_pde() function, which was using the PTE
function for computing the index, not the PDE one. I also fixed some
trailing white spaces in the code nearby.
=> [i386] Bug Fix: Bad PDE Get

include/target/ibm/pc.h
In this commit, I fix bad memory sizes for the i386-PC platform.
Overall, we were missing that the kernel spans over 2 Page Tables (lower
8MB) and the user memory that is available is actually computed
accordingly the size of the kernel and the size of the kernel page pool.
=> [i386-pc] Bug Fix: Bad Memory Sizes

include/nanvix/hal/target.h
In this commit, I have fixed missing memory symbols that are mandatory
in the HAL specification.
=> [hal] Bug Fix: Missing Mandatory Memory Constants

src/makefile
In this commit, I fix a small typo, for the debug release build. We were
missing the "D" to define the constant NDEBUG.
=> Bug Fix: Bad Debug Release Build

src/kernel/mm/mm.c
In this commit, I fix the build checking in the Kernel Page Pool address. The
user space area should end **before** the Kernel Page Pool starts.
=> Bug Fix: Bad Kernel Page Pool Address Checking

src/kernel/test/mm.c
In this commit, I fix the faulting injection test for freeing an invalid
page frame. We were supplying the page frame id instead of the page
frame number, and thus the test was failing with the bad error code.
Notice that I have also moved the previous test to the right  unit test
(bad free).
=> Bug Fix: Bad Invalid Free Frame Test

src/kernel/klib/kvsprintf.c
In this commit, I introduce a workaround in the kvsprintf() function in
order to avoid the linkage of LibGCC routines to compute integer
divisions. Machine code of these functions seems to be buggy in the k1b
architecture, causing invalid opcode exceptions to arise in kernel land.
While these workaround does remove the decimal formatted print output
from the kernel, it is important to note that we do not **really** need
rich output in kernel land.
=> Bug Fix: Avoid Linking LibGCC with the Kernel

src/kernel/hal/arch/or1k/setup.c
According to the issue #91, the OpenRISC architecture needs a TLB miss handler in the very early stages, since a kernel miss can occur during the kernel tests.
Thus, this PR introduces a private TLB handler that is set in the core setup and it's used until the HAL TLB handler is setup in the upool_init().
---
Just a note: if you notice, I also have to put the do_page_fault function in setup.c, since this function is also private. So far, this does not cause any issues, but when do_page_fault() is implemented, we have to rethink that, since this function relies on the HAL and not the architecture.
=> [or1k] Bug Fix: Initial TLB Handler

build/makefile.i386-pc, build/makefile.mppa256, include/target/kalray/mppa256.h, makefile, src/build/makefile.i386, src/build/makefile.k1bdp, src/build/makefile.k1bio, src/build/makefile.nanvix, src/build/makefile.or1k, src/kernel/build/makefile.i386-pc, src/kernel/build/makefile.mppa256, src/kernel/build/makefile.or1k-pc, src/kernel/makefile, src/libs/build/makefile.i386-pc, src/libs/build/makefile.mppa256, src/libs/build/makefile.or1k-pc, src/libs/makefile, src/test/build/makefile.i386-pc, src/test/build/makefile.mppa256, src/test/build/makefile.or1k-pc, src/test/makefile, tools/image/build-image.sh, tools/run/arch/mppa256.sh, tools/run/run.sh
In this commit, I have severely changed the building system, so as to
support building for IO clusters in the MPPA-256 target. Furthermore, I
have stripped down target-dependent rules, so that it becomes easier to
adapt the source tree to new targets.
=> [k1b] Enhancement: Build for IO Clusters

include/nanvix/mm.h, src/kernel/hal/arch/k1b/mmu.c
Previously, idle_pgdir was declared as an array, though it should be a
a pointer to the root page directory. This bug was causing bad page walk
in the k1b architecture, and thus it got fixed.
=> Bugfix bad idle pgdir

src/kernel/hal/arch/k1b/mmu.c
Previously, the root page table and page table directories were not
properly aligned at a page boundary, thus causing the page table
structures to be incorrectly filled up. In this commit, I have fixed
this problem by ensuring that these table are properly aligned when
building the binary file.
=> [k1b] Bug Fix: Misaligned Root Page Table

include/arch/k1b/context.h, src/kernel/hal/arch/k1b/hooks.S
Related Issues
--------------------
- [[k1b] Scratch Registers are Not Saved in the Execution Context](https://github.com/nanvix/microkernel/issues/113)
- [[k1b] Do Not Restore Stack Pointer](https://github.com/nanvix/microkernel/issues/114)
- [[k1b] mOS Uses 32-bit SPC Register](https://github.com/nanvix/microkernel/issues/115)
=> Bugfix k1b context

src/kernel/hal/arch/k1b/excp.c
Related Issues
--------------------
- [[k1b] Virtual Exceptions are not Dispatched](https://github.com/nanvix/microkernel/issues/117)
=> [k1b] Bug Fix: Dispatch Virtual Exceptions

include/arch/k1b/regs.h, include/nanvix/thread.h
Previously, we were forgetting to restore scratch registers pushed onto
the stack by the do_prologue macro. In this commit, I have fixed this
bug.
=>  [k1b] Bug Fix: Bad Function Epilogue

include/arch/k1b/excp.h, include/arch/or1k/excp.h, src/kernel/hal/arch/k1b/excp.c, src/kernel/hal/arch/or1k/excp.c, src/kernel/mm/page.c
In this commit, I have introduced a new operation in the exception
interface of the HAL that enables exceptions to be forwarded, thereby
enabling virtual exceptions to be fired.
=>  Enhancement: Exception Forwarding

src/kernel/hal/arch/or1k/core.c
When the function or1k_core_notify() is called from or1k_core_wakeup(), core_notify() tries to lock an already locked core, so this PR solves this by just moving the or1k_core_notify() to after the critical section...
=> [or1k] Bug Fix: Calling Notify When Core Is Already Locked

src/kernel/hal/arch/or1k/ompic.c, src/kernel/hal/arch/or1k/tlb.c
Previously we were having architecture-dependent files to include
non-architecture  dependent files, thus generating a cyclic building
dependency. In this commit I fixed this problem.
=> [or1k] Bug Fix: Cyclic Dependency

src/libs/makefile, src/libs/nanvix/errno.c
Although the kernel has the errno variable declaration, it's definition can not be found anywhere, thus, this PR introduces the variable as part of the library.
=> [or1k] Bug Fix: Errno Definition

src/kernel/hal/arch/or1k/hooks.S, src/libs/nanvix/or1k/_exit.c, src/libs/nanvix/or1k/thread.c
Until now the OpenRISC architecture does not have syscalls support, so this PR implements the syscall handler and the equivalent function wrappers.
It's highly recommended that this PR be merged after the PR #132, in order to avoid unexpected behaviors.
=> [or1k] Feature: OpenRISC Syscalls Support

include/nanvix.h, include/nanvix/mm.h, include/nanvix/signal.h, include/nanvix/syscall.h, src/kernel/pm/signal.c, src/kernel/sys/signal.c, src/kernel/sys/syscalls.c, src/libs/nanvix/signal.c, src/test/main.c, src/test/signal.c, src/test/test.h
Description
---------------
In this PR, @joaovicentesouto  introduces a simple signal interface dealing directly with the exceptions.
Specifically, only sigclt() function has implemented for use by the benchmarks of upcall..
Related Issues
--------------------
- [[kcalls] Signal Kernel Calls](https://github.com/nanvix/microkernel/issues/85)
- [[test] Unit Tests for Signals](https://github.com/nanvix/microkernel/issues/148)
=> [kcall] Signal Kernel Calls

build/optimsoc/make/makefile, build/qemu-openrisc/make/makefile
Description
---------------
The OpTiMSoC target was not building due the a wrong cluster in the makefile, this PR fixes it by changing to the right cluster in the build flags.
Related Issues
--------------------
- [[build] OpTiMSoC Build Is Failing](https://github.com/nanvix/microkernel/issues/151)
=> [build] Bug Fix: OpTiMSoC Build

include/nanvix/mm.h
Description
---------------
Since the optimsoc and qemu-openrisc targets still run in kernel mode, all data will belong to the kernel space, not user space. Therefore, the function mm_check_area() was leading to misbehaviour during the signals tests, since the sigact pointer belongs to the kernel space.
This PR fixes it by checking only for the kernel addresses.
=> [openrisc] Wrong Check in Memory Area

include/nanvix/thread.h, src/kernel/pm/thread.c
This P.R. aims to introduce kernel thread indexing without relying on core IDs.
- [[tm] Kernel Thread Number](https://github.com/nanvix/microkernel/issues/125)
=> [tm] Kernel Thread Number

build/makefile.run, docker/.env, docker/clean.yml, docker/debug-ccluster.yml, docker/debug-iocluster.yml, docker/debug.yml, docker/distclean.yml, docker/image-tests.yml, docker/run-ccluster.yml, docker/run-iocluster.yml, docker/run.yml, docker/test-ccluster.yml, makefile
This P.R. aims to introduce new Make rules relying on Docker Compose to leverage Nanvix Docker images.
* Docker Compose is required.
* Set the `DOCKER` environment variable to use Docker rules.
* If no target is specified then all targets will be processed. Several targets can be specified using the `TARGET` environment variable as usual (e.g. `export TARGET="qemu-riscv32 qemu-x86"`).
* [Docker Make Rules](https://github.com/nanvix/microkernel/issues/159)
=> Docker Make Rules

src/kernel/pm/thread.c
Added a limitation of 5 trials to `thread_create()`.
- [[thread] Retry Thread Create for a Finite Number of Times](https://github.com/nanvix/microkernel/issues/170)
=> [thread]  Retry Thread Create for a Finite Number of Times

include/nanvix/kernel/syscall.h
`NR_SYSCALLS` refers now to `NR_last_kcall` which represents the number of the last kernel call.
- [[kcall] Automatically Update Number of Kernel Calls](https://github.com/nanvix/microkernel/issues/176)
=> [kcall] Automatically Update Number of Kernel Calls

build/makefile.cflags, makefile, src/kernel/mm/frame.c, src/kernel/mm/kpool.c, src/kernel/mm/page.c
In this PR, there is the possibility to disable regression tests when building an installation from the above layers, using the makefile variable `SUPPRESS_TESTS = true`.
[[tests] Drop Regression Tests in Installation #181](https://github.com/nanvix/microkernel/issues/181)
=> [tests] Drop Regression Tests in Installation

include/nanvix/kernel/portal.h, src/kernel/noc/mailbox.c, src/kernel/noc/portal.c, src/kernel/noc/sync.c, src/kernel/sys/mailbox.c, src/kernel/sys/portal.c, src/kernel/sys/sync.c, src/kernel/sys/write.c
In this PR was made the separation between logic and semantic related to the parameters checks on NoC facilities (Mailbox, Portal and Sync). Now, logic checks are in `kernel/sys`, while semantic still in `kernel/noc`. 
Also, checks for pointers validity were added to avoid bad memory accesses from the user space.
- #191 - [[kcall] Check Mailbox Parameters](https://github.com/nanvix/microkernel/issues/191)
- #192 - [[kcall] Check Portal Parameters](https://github.com/nanvix/microkernel/issues/192)
- #194 - [[kcall] Check Sync Parameters](https://github.com/nanvix/microkernel/issues/194)
- #193 - [[kcall] Check for Pointers](https://github.com/nanvix/microkernel/issues/193)
=> [kcall] Check for Parameters on NoC Facilities

include/nanvix/kernel/mailbox.h, src/kernel/noc/mailbox.c, src/kernel/sys/mailbox.c
In this PR was added the support and multiplexing of virtual mailboxes. Now, the user can call multiple `open` and `create` calls, limited only by `VIRTUAL_MAILBOX_MAX` constant, that limits the number of virtual mailboxes that can be created. 
[ [ikc] Multiplex HW Mailboxes](https://github.com/nanvix/microkernel/issues/197)
=> [ikc] Multiplex HW Mailboxes

include/nanvix/kernel/syscall.h, src/kernel/init/main.c, src/kernel/sys/syscalls.c, src/test/lwip/lwip_manual.c
In order to start 'init' and consequently libnanvix, the architecture must have at least 2 cores, not three as it was before, so targets like qemu-openrisc can work without any problems.
- [[tests] Set Network Tests as Manual](https://github.com/nanvix/microkernel/issues/209)
=> Launching Init Thread with Two or More Cores

include/nanvix/kernel/portal.h, src/kernel/noc/mailbox.c, src/kernel/noc/portal.c, src/kernel/sys/portal.c
In this PR was added the support and multiplexing of virtual portals. Now, the user can call multiple open and create calls, limited only by KPORTAL_MAX constant, that limits the number of virtual portals that can be created.
In addition, was added the function `do_portal_search()` to simplify the logic when looking for already existing HW portals on `_do_portal_create()` and `_do_portal_open()`.
[#198 - [ikc] Multiplex HW Portals](https://github.com/nanvix/microkernel/issues/198)
[#190 - [ikc] Portal Search](https://github.com/nanvix/microkernel/issues/190)
=> [ikc] Multiplex HW Portals

include/nanvix/kernel/sync.h, src/kernel/noc/mailbox.c, src/kernel/noc/sync.c, src/kernel/sys/sync.c
In this PR was added the support and multiplexing of virtual synchronization points. Now, the user can call multiple open and create calls, limited only by KSYNC_MAX constant, that limits the number of virtual syncs that can be created.
In addition, was added the function `do_sync_search()` to simplify the logic when looking for already existing HW synchronization points on `_do_sync_create()` and `_do_sync_open()`.
[#199 - [ikc] Multiplex HW Syncs](https://github.com/nanvix/microkernel/issues/199)
[#211 - [ikc] Sync Search](https://github.com/nanvix/microkernel/issues/211)
=> [ikc] Multiplex HW Syncs

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/syscall.h, src/kernel/noc/mailbox.c, src/kernel/sys/mailbox.c, src/kernel/sys/syscalls.c
In this PR was implemented the correct addressing scheme of messages to different Virtual Mailboxes, based on ports vinculated to the HW mailboxes.
Below were list some noticeable changes.
- Added `port` parameter on `do_vmailbox_create(int local, int port)` signature;
- Added `remote_port` parameter on `do_vmailbox_open(int remote, int remote_port)`;
- `KMAILBOX_MESSAGE_SIZE` is the new mailbox size constant that defines the mailbox message size. It considers the `MAILBOX_MSG_SIZE` exported by the Hal, and subtracts the Kernel header size.
- Added a `VMAILBOX_IS_USED` check before each kernel function that uses Vmailboxes IDs, to avoid operations using unused virtual mailboxes.
Closes #218 - [[ikc] Multiplex Mailbox Messages](https://github.com/nanvix/microkernel/issues/218)
=> [ikc] Mailbox Messages Multiplex Bugfix

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/noc.h, include/nanvix/kernel/portal.h, include/nanvix/kernel/sync.h, src/kernel/init/main.c, src/kernel/mm/page.c, src/kernel/noc/mailbox.c, src/kernel/noc/noc.c, src/kernel/noc/portal.c, src/kernel/noc/sync.c, src/kernel/sys/sync.c
In this PR, we enabled distinct threads to communicate using messages in the same cluster adding the message forwarding for Mailboxes and Portals. These operations occur locally using shared memory and so don't need to use the NoC and pass by the HAL.
- Closes #224 - [[ikc] Forward Mailbox Messages to Threads within a Cluster](https://github.com/nanvix/microkernel/issues/224)
- Closes #225 - [[ikc] Forward Portal Operations to Threads within a Cluster
](https://github.com/nanvix/microkernel/issues/225)
=> [ikc] Messages Forwarding

include/nanvix/kernel/syscall.h, src/kernel/noc/mailbox.c, src/kernel/noc/portal.c, src/kernel/noc/sync.c, src/kernel/sys/noc.c, src/kernel/sys/syscalls.c
In this PR, I remove the dependency of the coreid to get the local `nodenum`. Also, I remove the unnecessary `kernel_node_set_num` and its redundant code.
=> Enhancement: Removes nodenum exchange

include/nanvix/kernel/syscall.h, src/kernel/init/main.c, src/kernel/sys/syscalls.c
In this PR, I add a function to initialize the syscall system because multiple init on a semaphore can introduce an undefined behavior on Unix.
=> [kcall] Bad Semaphores Initialization of Syscall Table

include/nanvix/kernel/kernel.h, include/nanvix/kernel/mailbox.h, include/nanvix/kernel/noc.h, include/nanvix/kernel/portal.h, include/nanvix/kernel/syscall.h, src/kernel/noc/vmailbox.c, src/kernel/noc/vportal.c, src/kernel/sys/noc.c, src/kernel/sys/syscalls.c
This PR adds the `comm_get_port` kernel call, to attend the necessity of the upper layers on knowing the allocated port in a portal_open call.
=> [ikc] New Communicator Get_Port Kcall

src/kernel/noc/active.c, src/kernel/noc/active.h, src/kernel/noc/communicator.c, src/kernel/noc/communicator.h, src/kernel/noc/mailbox.c, src/kernel/noc/mbuffer.c, src/kernel/noc/port.c, src/kernel/noc/port.h, src/kernel/noc/portal.c
In this PR, a fair-write system was implemented for the active communicators interface, to avoid indefinite postponement for some threads. It is implemented using a circular FIFO for write requests, granting the channel fair use.
=> [ikc] Enhancement: Active Fair Write

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/portal.h, src/kernel/noc/active.c, src/kernel/noc/active.h, src/kernel/noc/mailbox.c, src/kernel/noc/mbuffer.c, src/kernel/noc/mbuffer.h, src/kernel/noc/port.h, src/kernel/noc/portal.c, src/kernel/noc/vmailbox.c, src/kernel/noc/vportal.c
In this PR, we introduce auxiliary pools to use on local communication. The auxiliary pool is a subset of all mbuffers available. Besides that, we add an aging system to mbuffer consume the messages in incoming order.
=> [ikc] Ordered and Auxiliary mbuffer Pool

include/nanvix/kernel/sync.h, include/nanvix/kernel/syscall.h, src/kernel/noc/sync.c, src/kernel/sys/sync.c, src/kernel/sys/syscalls.c
In this PR, I refactor the sync system to create/open syncs during the runtime. Now, the possibility of nodes lists and interleaved operations increases. However, we must take care that sync points exist before performing sync operations.
[Enhancement: Sync system refactor (HAL PR)](https://github.com/nanvix/hal/pull/582)
=> Enhancement: Sync system refactor

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/portal.h, include/nanvix/kernel/sync.h, src/kernel/noc/noc.c, src/kernel/noc/sync.c, src/kernel/noc/vmailbox.c, src/kernel/noc/vportal.c, src/kernel/sys/mailbox.c
In this PR, I increase the number of virtual mailbox ports to share between the mailbox, portal, and sync when using only the mailbox ports for communication. If it is disabled, all ports are available for the mailboxes.
I also allowed a variable mailbox size within the maximum size previously stipulated. In practice, only the initial checks change, the rest continue with the same behavior.
=> [ikc] Support for Mailbox Communication Only

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/portal.h, src/kernel/noc/active.h, src/kernel/noc/communicator.c, src/kernel/noc/communicator.h, src/kernel/noc/mailbox.c, src/kernel/noc/mailbox.h, src/kernel/noc/mbuffer.c, src/kernel/noc/mbuffer.h, src/kernel/noc/portal.c, src/kernel/noc/portal.h, src/kernel/noc/vmailbox.c, src/kernel/noc/vportal.c
In this PR we provide a way for the user to specify from which source it wants to receive a message during a `mailbox_read()` operation. This can be achieved by calling `kmailbox_ioctl()` using the `KMAILBOX_IOCTL_SET_REMOTE` operation. It sets the `remote_addr` of the specified mailbox  to the specified source and will configure it to read a message sent by that. This change is valid for a single read (similar to `portal_allow()`), and must be redone for successive reads from the same source, and can also specify to look only for specific ports or specific nodes independently, passing any of the constants `MAILBOX_ANY_SOURCE` or `MAILBOX_ANY_PORT` to the IOCTL operation. 
**Note:** Using this IOCTL operation and passing MAILBOX_ANY_SOURCE and MAILBOX_ANY_PORT as parameters in the same …
=> [ikc] Specifying Mailbox Source

src/kernel/noc/mailbox.c, src/kernel/noc/mbuffer.h, src/kernel/noc/portal.c
In this PR, we force IKC buffers to be aligned on 8-byte addresses. This change benefits the architectures that work better with aligned memories.
=> [ikc] Enhancement: Align IKC buffers on 8-byte addresses

include/nanvix/kernel/mailbox.h, include/nanvix/kernel/portal.h
This PR is a small patch to increase the IKC Structures Ports to 24 instead 16, making available a new special range of ports to be used for general purpose, without risking interference with system used ports.
- Closes #270 - [[ikc] Increase IKC Structures Port Range](https://github.com/nanvix/microkernel/issues/270)
- #271 - [[ikc] Widening IKC Ports Range breaks execution in MPPA-256](https://github.com/nanvix/microkernel/issues/271)
=> [ikc] Increase Number of Ports for Abstractions

include/nanvix/kernel/syscall.h, include/nanvix/kernel/thread.h, src/kernel/init/main.c, src/kernel/pm/multithread.c, src/kernel/pm/singlethread.c, src/kernel/pm/thread.c, src/kernel/sys/sleep.c, src/kernel/sys/syscalls.c, src/kernel/sys/thread.c
In this PR, I implement a thread scheduler used on architecture that supports multithreading (see `CORE_SUPPORTS_MULTITHREADING` constant in nanvix/hal).
Briefly, I add the following changes:
- Rename the old thread management file from `pm/thread.c` to `pm/singlethread.c`
- Modify the single thread management to use `context_create` and `context_switch_to` functions to perform the schedule of user thread. This makes it possible to have more user threads than physical cores. The implementation is in the `pm/multithread.c` file.
- Add the `thread_yield` function to allow threads to voluntarily yield the core to another thread.
[[core] Feature: Introduce context switching mechanism #621](https://github.com/nanvix/hal/pull/621)
Closes #226
=> [tm] Thread Scheduler

src/kernel/noc/vmailbox.c
In this PR, I reset the remote address every time that a mailbox read is completed.
Before this fix, an application could set a specific address that's will be not reset, introducing a deadlock.
=> [ikc] Reset Communication Parameters When Mailbox Read Completes

src/kernel/noc/communicator.c
In this PR, a new security check is added to the Set_Remote IOCTL operation, to avoid a double Set_Remote, or applying this operation for input portals, which would be erroneous.
=> [ikc][bugfix] New Security Check to IOCTL Set Remote Operation

src/kernel/pm/exception.c
In this PR, I add a check that verifies if the master thread tries to wait for exception treatment. If it is true, then we enter a _kernel panic_ state.
Closes #296
=> [pm] Enter a Panic state if the master thread throws an exception.

include/nanvix/kernel/hal/arch/x86/memory.h
This commit fixes the physical address space. We were skipping an additional page table between kernel and kpool address ranges.
=> [hal] Bad Physical Memory Layout

src/kernel/mm/frame/mod.c
This PR fixes the bug we were performing a bad check when allocating page frames.
=> [kernel] Wrong Bitmap Check on Page Frame Allocation

include/nanvix/kernel/log.h, src/kernel/Makefile, src/kernel/log/log.c
The kernel log subsystem is declared in the header file `<nanvix/kernel/log.h>`.
It is exposed through the `log()` macro that recieves one of the five avaible message levels (`DEBUG`, `ERROR`, `INFO`, `TRACE`, `WARN`) and a format string with a message.
The message is printed to the standard output and shall follow the behaviour specified in issue #352.
=> [kernel] F: Log subsystem

src/kernel/pm/process.c
Attempt of fixing the problem described in the issue #393
=> Fix attempt of `process_exit()` causing a use after free

src/kernel/pm/thread.c
This PR addresses a bug reported by @rafael0121 in issue #415, implementing his fix suggestion.
=> [pm] B: thread_exit() trying to access negative index

src/kernel/hal/arch/lpic.c
Change the "panic" function that cause the stop in boot, to a "info" function. 
close #423
=> [hal] E: Continue boot even if cpu support x2apic

src/mboot/mod.rs
The parse methods were separated in different functions, improving modularity and maintainability.
This PR closes #426
=> [boot] E: Split mboot parser function

Cargo.toml
- Do not rely on default features for `arch`.
=> [contrib] No Default Features for `arch`

src/hal/mod.rs, src/hal/platform/bootinfo.rs, src/hal/platform/microvm.rs, src/hal/platform/pc/mboot/acpi.rs, src/hal/platform/pc/mboot/basic_mem_info.rs, src/hal/platform/pc/mboot/mboot_tag.rs, src/hal/platform/pc/mboot/memory_map.rs, src/hal/platform/pc/mboot/mod.rs, src/hal/platform/pc/mboot/module.rs, src/hal/platform/pc/mod.rs, src/kmain.rs
Parse the multiboot tag [Basic Memory Information](https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html#Basic-memory-information), to get the `mem_lower` entrie that store the size of the available lower physical memory region starting of the address 0x0. So, ensure that the hardcode memory regions are available for use. This closes #435 
- src/hal/mod.rs
- src/hal/platform/bootinfo.rs
- src/hal/platform/microvm.rs
- src/hal/platform/pc/mboot/mod.rs
- src/hal/platform/pc/mod.rs
- src/kmain.rs
- src/hal/platform/pc/mboot/basic_mem_info.rs
=> [hal] E: Check lower memory regions are available

Cargo.toml, src/kcall/handler.rs, src/pm/process/manager.rs, src/sys/config.rs
This PR introduces a simple throttling heuristic for IKC messages to prevent the kernel from running out of memory under heavy load.
=> [pm] Thottle IKC Messages

src/sys/mod.rs
This PR gates `kcall` module behind the `target_os` feature. This enales kernel library to use in hosted environments.
=> [build] Gate `kcall` Behind Target OS

src/kcall/handler.rs, src/sys/pm/pid.rs
This PR renames the special identifier of the very first user-level process from `PROCD` to `INITD`.
The kernel does not rely on the assumption that the very-first user-level process is running a process daemon, thus the special identifier should not be named so.
=> [pm] Renaming `PROCD` to `INITD`

src/sys/config.rs, src/sys/ipc/message.rs
This PR adds the following changes:
- Rename `TOTAL_SIZE` to `IPC_MESSAGE_SIZE`
- Move `IPC_MESSAGE_SIZE` to kernel configuration module.
=> [config] Move `IPC_MESSAGE_SIZE` to Kernel Configuration Module

src/sys/ipc/message.rs
This PR removes the hard-code size of IPC messages in favor of `IPC_MESSAGE_SIZE` constant.
=> [ipc] No Hard-Code `IPC_MESSAGE_SIZE`

Cargo.toml, src/mm/virt/vmem.rs
This PR closes https://github.com/nanvix/kernel/issues/457
This PR introduces the following changes:
- Check for zero-length copies.
- Enable copies spanning acros page boundaries.
- Check end address of copies
 
=> Enable Copy from User Space Spanning Across Pages[mm] 
