include/arch/i386/mmu.h

In this commit, I introduce a function in the MMU interface of i386 to
get the frame of a page. Additionally, I fixed some trailing white
spaces.

[i386] Enhancement: Improving MMU Interface

---

build/makefile.i386-pc
src/makefile

In this PR I introduce some small improvements in the building system

Enhancement: Improving Build Options

---

include/nanvix/mm.h
src/kernel/makefile.i386-pc
src/kernel/mm/frame.c
src/kernel/mm/kpool.c
src/kernel/mm/mm.c
src/kernel/mm/page.c
src/kernel/test/mm.c

**Description**
In this pull request, I introduce the Memory Management (MM) system.
**Related Issues**
https://github.com/nanvix/microkernel/issues/14
https://github.com/nanvix/microkernel/issues/15
https://github.com/nanvix/microkernel/issues/16
https://github.com/nanvix/microkernel/issues/29
https://github.com/nanvix/microkernel/issues/30
https://github.com/nanvix/microkernel/issues/31

Feature: Memory Management System

---

src/kernel/pm/thread.c

Previously, we had a single conditional variable for signalling that a
joining thread was ripped out a thread that was exiting. Thus, if more
than one thread was exiting, all of them would be unblocked, even if
no thread was joining them. In this commit, I have fixed this problem.

Bug Fix: All Exiting Threads Unblock

---

include/nanvix/const.h
src/kernel/hal/arch/k1b/ivt.c
src/kernel/init/main.c

In this commit, I have introduced a kernel stack for handling
exceptions.

[k1b] Enhancement: Kernel Exception Stack

---

src/kernel/pm/thread.c

This pull request aims to make use of the enhancement introduced in commit 0b9778fa07ea305450b5db068060448e144fc1b4.
* [[tm] Rely on Null Thread ID](https://github.com/nanvix/microkernel/issues/128)

[tm] Rely on Null Thread ID

---

src/kernel/sys/sync.c
src/libs/nanvix/mailbox.c
src/libs/nanvix/portal.c
src/libs/nanvix/sync.c
src/test/kmailbox.c
src/test/kportal.c
src/test/ksync.c

In this PR, I fix some small bugs on the compilation for MPPA-256 and communication abstraction's tests.

Bugfix: kcalls and communication tests

---

include/nanvix/kernel/syscall.h
src/kernel/sys/noc.c
src/kernel/sys/syscalls.c

In this PR, I add kernel calls to get/set the node number associated with a core.

[ikc] Kernel Calls to Get/Set Node Number

---

include/nanvix/kernel/kernel.h
include/nanvix/kernel/mailbox.h
include/nanvix/kernel/portal.h
include/nanvix/kernel/sync.h
src/kernel/noc/mailbox.c
src/kernel/noc/portal.c
src/kernel/noc/sync.c
src/kernel/sys/mailbox.c
src/kernel/sys/portal.c
src/kernel/sys/sync.c

In this PR, I improve sync abstraction and allow mailbox and portal do create/open multiple times a abstraction with the same parameters. I also fix some bugs.

[ikc] Allow Multiple Create/Open Operations

---

include/nanvix/kernel/mailbox.h
include/nanvix/kernel/portal.h
include/nanvix/kernel/syscall.h
src/kernel/noc/mailbox.c
src/kernel/noc/portal.c
src/kernel/sys/mailbox.c
src/kernel/sys/noc.c
src/kernel/sys/portal.c
src/kernel/sys/syscalls.c

In this PR, I introduce ioctl operations (volume/latency) of the mailbox and portal abstractions.

[ikc] Support for IO Control Operations

---

src/kernel/noc/mailbox.c

In this PR, a function `do_mailbox_search` was added to traverse the mailbox table and look for an already existing mailbox, returning it's number in the table or a negative number otherwise.
This function is now called on `do_mailbox_create()` and `do_mailbox_open()`.
[#189 - [ikc] Mailbox Search](https://github.com/nanvix/microkernel/issues/189)

[ikc] Mailbox Search

---

include/nanvix/kernel/mailbox.h
include/nanvix/kernel/portal.h
src/kernel/noc/mailbox.c
src/kernel/noc/noc.c
src/kernel/noc/portal.c

In this PR, we finished the HAL IKC abstractions initialization of Portal and Mailbox. Now, it is dinamically initialized by `noc_init` function on system startup initializing the kernel structures with the HW file descriptors.
Closes #229 - [[ikc] Dynamic Initialization for Sync, Mailbox and Portal](https://github.com/nanvix/microkernel/issues/229)

[ikc] Facilities Dynamic Initialization

---

src/kernel/noc/mailbox.c

In this PR, I normalize the naming of physical and virtual resources and fix the use of wrong locks on the virtual allocation of mailboxes.

[noc] Bugfix: Wrong Locks in Virtual Mailbox Allocation

---

build/unix64/make/makefile.cflags

In this PR, I select CFLAGS manually because -O3 is breaking the execution on Unix.

[unix64] Unsafe Optimizations

---

src/kernel/noc/active.c
src/kernel/noc/active.h
src/kernel/noc/communicator.c
src/kernel/noc/communicator.h
src/kernel/noc/mailbox.c
src/kernel/noc/mailbox.h
src/kernel/noc/mbuffer.c
src/kernel/noc/mbuffer.h
src/kernel/noc/vmailbox.c

In this PR, Mailbox operations were refactored in virtual and physical operations. Also, the first draft of common generalizations for IPC abstractions were made, namely:
- Mbuffers Generalization
- Ports abstraction
- Virtual communicators abstraction
- Active communicators abstraction
Also, enhancements to the Mailbox interface were added, like use of resources instead of hand controlled flags.

[ikc] Virtual/Physical Mailbox Refactor

---

include/nanvix/kernel/noc.h
src/kernel/noc/active.c
src/kernel/noc/active.h
src/kernel/noc/communicator.c
src/kernel/noc/mailbox.c
src/kernel/noc/mbuffer.h
src/kernel/noc/noc.c
src/kernel/noc/portal.c
src/kernel/noc/portal.h
src/kernel/noc/vportal.c

In this PR, Portal operations were refactored in virtual and physical operations, adapting the abstractions implemented for Mailboxes. The refactor involved:
- Mbuffers Generalization
- Ports abstraction
- Virtual communicators abstraction
- Active communicators abstraction
Also, enhancements to the Portal interface were added, like use of resources instead of hand controlled flags.

[ikc] Virtual/Physical Portal Refactor

---

include/nanvix/kernel/mailbox.h
src/kernel/noc/active.c
src/kernel/noc/active.h
src/kernel/noc/communicator.c
src/kernel/noc/communicator.h
src/kernel/noc/mailbox.c
src/kernel/noc/mailbox.h
src/kernel/noc/mbuffer.c
src/kernel/noc/mbuffer.h
src/kernel/noc/port.c
src/kernel/noc/port.h
src/kernel/noc/portal.c
src/kernel/noc/portal.h
src/kernel/noc/vmailbox.c
src/kernel/noc/vportal.c

In this PR, I refactor the dependency of the headers of NoC services and their documentation. Also, I abstract the header of the mbuffer to be common between mailbox and portal services.

[ikc] Refactoring Headers and Documentation

---

.travis.yml
include/nanvix/kernel/mailbox.h
include/nanvix/kernel/portal.h
src/kernel/noc/active.c
src/kernel/noc/active.h
src/kernel/noc/communicator.c
src/kernel/noc/communicator.h
src/kernel/noc/mailbox.c
src/kernel/noc/mailbox.h
src/kernel/noc/mbuffer.c
src/kernel/noc/mbuffer.h
src/kernel/noc/port.c
src/kernel/noc/port.h
src/kernel/noc/portal.c
src/kernel/noc/portal.h
src/kernel/sys/noc.c

In this PR, I fix the message size definition of the portal/mailbox.
[[target] Bugfix: Missing constants and checks](https://github.com/nanvix/hal/pull/584)

[ikc] Message Sizes

---

src/kernel/pm/thread.c

In this PR, we remove the need for `thread_exit` to block until a join is given. The exit of a thread also indicates that the core is about to be reset by calling the `core_release` function.
The `thread_join`, in turn, returns successfully whenever a `tid` is valid and only blocks if the target thread is still running.
- Closes https://github.com/nanvix/microkernel/issues/252
[[cluster] Bugfix: Core reset in two phases](https://github.com/nanvix/hal/pull/585)

[tm] Unable to Create Kernel Thread in Stress Tests

---

include/nanvix/kernel/mailbox.h
include/nanvix/kernel/noc.h
include/nanvix/kernel/portal.h
include/nanvix/kernel/sync.h
include/nanvix/kernel/syscall.h
src/kernel/noc/communicator.c
src/kernel/noc/communicator.h
src/kernel/noc/sync.c
src/kernel/noc/vmailbox.c
src/kernel/noc/vportal.c
src/kernel/sys/sync.c
src/kernel/sys/syscalls.c

In this PR, I add IOCTL interface to the Sync module. Also, I introduce operation counters that can be accessed by the IOCTL interface.
[[ikc] IOCTL Does not Check For Invalid Pointers #257](https://github.com/nanvix/microkernel/issues/257)

[ikc]Sync's IOCTL and Operation Counters in IOCTL

---

src/kernel/noc/active.c
src/kernel/noc/mailbox.c
src/kernel/noc/mbuffer.c
src/kernel/noc/mbuffer.h
src/kernel/noc/portal.c

In this PR, I assign the latency of the communication through portal/mailbox to the buffer eliminating interference between ports.

[ikc] Interference on Latency Between Differents Ports

---

src/kernel/noc/active.c

In this PR, I include the time o intermediary copies to communication latencies.

[ikc] Get Copy Time on Communication Latencies

---

include/nanvix/kernel/thread.h
src/kernel/pm/multithread.c
src/kernel/pm/singlethread.c
src/kernel/sys/thread.c

I added a function to get the current thread id.
Closes #282

[pm] Enhancement: Add a function to get the current Thread ID directly

---

include/nanvix/kernel/thread.h
src/kernel/pm/multithread.c

I made threads to be dynamically allocated in memory. A new thread state was also added: the THREAD_ZOMBIE, that indicates that the thread can be released by another thread.
Closes #283

[pm] Dynamically Allocate Thread Stacks

---

include/nanvix/kernel/thread.h
src/kernel/makefile
src/kernel/pm/thread/common.c
src/kernel/pm/thread/common.h
src/kernel/pm/thread/multithread.c
src/kernel/pm/thread/singlethread.c

In this PR, I implemented the possibility for using the return values of threads both in single-thread and multi-threaded. 
This PR closes #254

[pm] Thread Return Value

---

include/nanvix/kernel/config.h

Updated synchronization primitives to support condition variable functions

[thread] Updating Synchronization Primitives

---

src/kernel/noc/active.c

[tm] Enhancement: Global clock error (Issue #277)

---

include/nanvix/kernel/config.h
include/nanvix/kernel/excp.h
include/nanvix/kernel/mailbox.h
include/nanvix/kernel/portal.h
include/nanvix/kernel/syscall.h
include/nanvix/kernel/thread.h
src/kernel/dev/dev.c
src/kernel/init/main.c
src/kernel/makefile
src/kernel/noc/active.c
src/kernel/noc/active.h
src/kernel/pm/exception.c
src/kernel/pm/task/delta_queue.c
src/kernel/pm/task/delta_queue.h
src/kernel/pm/task/periodic_queue.c
src/kernel/pm/task/periodic_queue.h
src/kernel/pm/task/task.c
src/kernel/pm/thread/common.c
src/kernel/pm/thread/preemptive.c
src/kernel/sys/exception.c
src/kernel/sys/syscalls.c
src/kernel/sys/task.c

Introduce Task Engine (disabled by default)

Feature: Introduce Task Engine (disabled by default)

---

README.md

This PR adds a status badge in README for x86 GitHub Actions workflow.

[doc] x86 Workflow Status Badge in Readme

---

Makefile
scripts/setup/ubuntu.sh

This PR add a check-format rule to the build system.

[build] Check Format on Build

---

include/arch/x86/cpu/gdt.h
include/arch/x86/cpu/tss.h
include/arch/x86/cpu/types.h
include/nanvix/kernel/hal/arch/x86/gdt.h
include/nanvix/kernel/hal/arch/x86/tss.h
src/kernel/hal/arch/cpu.c
src/kernel/hal/arch/gdt.c
src/kernel/hal/arch/tss.c
src/kernel/hal/interrupt.c
src/kernel/kcall.c
src/kernel/pm/thread.c

This PR refactors the following components:
- x86 CPU types
- x86 GDT
- x86 TSS

[x86] Refactoring

---

.github/workflows/x86.yml
src/kernel/kcall.c

This PR adds a test job in the CI workflow.

[ci] Test Job for GitHub Actions

---

include/nanvix/kernel/hal/mmu.h
src/kernel/Makefile
src/kernel/hal/mmu/mod.c
src/kernel/hal/mmu/mod.h
src/kernel/hal/mmu/test.c

This PR refactors the MMU and add some unit tests to it.

[hal] Refactoring MMU

---

src/kernel/mm/memory.c

This PR solves wrong accesses in the memory layout structure.

[mm] Bad Access in Memory Layout Structure

---

include/nanvix/kernel/kmod.h
src/kernel/kmod.c

This PR introduces a kernel component for managing the registration of kernel modules.

[kernel] Kernel Modules

---

include/nanvix/kernel/kmod.h
src/kernel/kmod.c

This PR adds enhancements to the kernel module component.

[kernel] Enhancements to Kernel Module Component

---

include/nanvix/kernel/lib.h
src/kernel/pm/semaphore.c

This PR fixes minor bugfixes that concerns building.

[kernel] Minor Bug Fixes on Kernel Build

---

src/kernel/kmain.c

This PR fixes the bug where we were not clearing the BSS at system startup.

[kernel] Clear BSS

---

include/nanvix/kernel/kargs.h
src/kernel/hal/arch/boot.S
src/kernel/hal/arch/mboot.c
src/kernel/kmain.c

This PR introduces kernel arguments.

[hal] Kernel Arguments

---

include/nanvix/kernel/lib.h
include/nanvix/kernel/mm/frame.h
src/kernel/mm/frame/mod.c
src/kernel/mm/frame/test.c

This PR introduces various enhancements for page frames module.

[kernel] Various Enhancements to Page Frames Module

---

include/elf.h
src/kernel/elf.c

This PR introduces initial support for loading ELF files.

[kernel] ELF Load Support

---

src/kernel/mm/memory.c

This PR introduces an enhancement that maps kernel modules when building the root address space.

[kernel] Map Kernel Modules

---

src/kernel/hal/arch/mmu.c

This PR fixes a bug where we were not setting the writable bit in page directory level.

[hal] Set Write Bit in Page Directory Level

---

include/nanvix/kernel/hal/interrupt.h
src/kernel/hal/arch/int.c

This PR introduces capabilities for forging an interrupt stack.

[hal] Forge Interrupt Stack

---

include/nanvix/kernel/mm.h
include/nanvix/kernel/mm/virtmem.h
src/kernel/mm/virtmem.c

This PR adds the virtual memory component.

[kernel] Virtual Memory Component

---

scripts/setup/qemu.sh

Update the QEMU downloaded by script qemu.sh. 
**QEMU 8.0.0 -> 8.1.0**
#380

[build] B: Setup QEMU 8.1.0

---

include/nanvix/kernel/kcall.h
src/kernel/Makefile
src/kernel/kcall/mod.c
src/kernel/kcall/mod.h
src/kernel/kcall/sem/semctl.c
src/kernel/kcall/sem/semget.c
src/kernel/kcall/sem/semop.c
src/libnanvix/src/kcall/mod.rs
src/libnanvix/src/pm/mod.rs
src/servers/test/src/test.rs

- This PR closes #389
- Implemented *Semaphore Kernel Calls*, and added test functions in server *test* .

Feature kernel semaphore syscalls

---

include/nanvix/kernel/pm/semaphore.h
src/kernel/pm/semaphore.c

- This PR closes #387 
- Implemented Semaphore tables, structures and handler functions.

Feature kernel semaphore semtable

---

include/nanvix/kernel/kcall.h
include/nanvix/kernel/pm.h
include/nanvix/kernel/pm/process.h
include/nanvix/kernel/pm/thread.h
include/nanvix/types.h
src/kernel/kcall/mod.c
src/kernel/kcall/mod.h
src/kernel/kcall/thread.c
src/kernel/pm/process.c
src/kernel/pm/thread.c

This PR is an initial solution to the issue described at #383.

[pm] E: Isolate Thread Data Structure from Process

---

include/nanvix/kernel/pm/semaphore.h
src/kernel/kcall/sem/semget.c
src/kernel/pm/semaphore.c
src/servers/test/src/test.rs

- This PR closes #388 
- Changed return in function `semaphore_get()`, now this function return the key if a key was found by `key_check()`.
- Implemented Semaphore get function and improve test.

[pm] F: Kernel Semaphore Semget

---

include/nanvix/kernel/hal.h
include/nanvix/kernel/hal/uthread.h
include/nanvix/kernel/kcall.h
include/nanvix/kernel/mm/memory.h
include/nanvix/kernel/pm/process.h
include/nanvix/kernel/pm/thread.h
src/kernel/hal/arch/hooks.S
src/kernel/hal/arch/uthread.c
src/kernel/kcall/mod.c
src/kernel/kcall/mod.h
src/kernel/kcall/thread.c
src/kernel/pm/process.c
src/kernel/pm/thread.c
src/libnanvix/src/kcall/mod.rs
src/libnanvix/src/pm/kcall.rs
src/libnanvix/src/pm/mod.rs
src/libnanvix/src/pm/types.rs
src/servers/test/src/test.rs

This PR aims to close the issue #406.

[pm] F: Multiple threads per process support

---

src/kernel/ipc/mailbox/omailboxes.c

Fixed logic error in function omailboxes_lookup.

[IPC] F: Fixed omailboxes_lookup function

---

src/servers/test/src/lib.rs
src/servers/test/src/readerswriters.rs

- This PR closes #409 
- Implement readers and writers problem.
- A new module "readerswriters" in server test was created.
- src/servers/test/src/lib.rs
- src/servers/test/src/readerswriters.rs

[test] F: Implement readers and writers problem

---

scripts/setup/qemu.sh

- This PR closes #419 
- Change old link to [new link.](https://download.qemu.org/)
- Change tar option "j" to "J" for files compressed with xz.

[build] E: Update download QEMU link

---

src/hal/platform/pc/mboot/mod.rs

This PR fixes build warnings and code formatting issues.

[build] Fixing Build Warnings and Code Formatting

---

src/mm/virt/vmem.rs

This PR fixes mutliple issues in the `copy_to_user_unaligned()` function:
- Check for zero-length copies
- Check if source address range does not lie in kernel space
- Check if destination address range does not lie in user space
- Support copies larger than a page

[mm] Multiple Fixes on Copy to User Unaligned

---

src/kpanic.rs

This PR introduces shutdown on panic.

[pm] Shutdown on Panic

---

Cargo.toml

This PR updates the following dependencies:
- `cc` crate
- `build` system

[contrib] Updating Dependencies

---

src/event/manager.rs
src/sys/event/information.rs
src/sys/ipc/message.rs

This PR adds a status error code to the header of an IPC message.

[ipc] Add Status Code to IPC Message

---

.github/workflows/x86-debug.yml
.github/workflows/x86-release.yml
Makefile

This PR changes the build system to use system-wide QEMU installation if available.

[build] Use System-Wide QEMU Installation If Available

---

src/ipc/kcall.rs
src/stdio.rs
src/sys/ipc/message.rs
src/sys/ipc/typ.rs

This PR introduces multiple improvements to the `Message` structure:
- Support access to unaligned fields in `Message`.
- Encode message types in a single byte
- Pack `Message` structure and reorder fields for better alignment.

[ipc] Improvements to `Message`

---

Cargo.toml

This PR closes https://github.com/nanvix/kernel/issues/455.

[contrib] Updating Build System
